eureka:
  client:
    serviceUrl:
      defaultZone: ${vcap.services.eureka-service.credentials.uri:http://localhost:8761}/eureka/

security:
  oauth2:
    resource:
      jwt:
        keyValue: secret
    client:
      client-id: # Necessary for autoconfiguration to create OAuth2RestOperations bean for forwarding the tokens
