spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/gerar2/cf-poc
          search-paths: /configuration

server:
  port: 8081

